### ISSUE TITLE
Cannot Locate Symbol mmap64

### ISSUE THREAD

**Issue by Kandr0s** [sqlcipher/sqlcipher-android-tests#24]
When I try to start the Test-App on my Android Emulator (Api 19), it crashes.
3.5.7 Worked
3.5.8 Crashes

FATAL EXCEPTION: AsyncTask #1
                                                                          Process: net.zetetic.sqlcipher.test, PID: 6904
                                                                          java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                              at java.lang.Thread.run(Thread.java:841)
                                                                           Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "mmap64" referenced by "libsqlcipher.so"...
                                                                              at java.lang.Runtime.loadLibrary(Runtime.java:364)
                                                                              at java.lang.System.loadLibrary(System.java:526)
                                                                              at net.sqlcipher.database.SQLiteDatabase$1.loadLibraries(SQLiteDatabase.java:213)
                                                                              at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:230)
                                                                              at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:209)
                                                                              at net.sqlcipher.database.SQLiteDatabase.loadLibs(SQLiteDatabase.java:202)
                                                                              at net.zetetic.tests.TestSuiteRunner.runSuite(TestSuiteRunner.java:52)
                                                                              at net.zetetic.tests.TestSuiteRunner.doInBackground(TestSuiteRunner.java:33)
                                                                              at net.zetetic.tests.TestSuiteRunner.doInBackground(TestSuiteRunner.java:16)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                              at java.lang.Thread.run(Thread.java:841)

**Comment by developernotes** [comment]
Hi @Kandr0s 

Thank you for the error report, we will look into this further.

**Comment by developernotes** [comment]
Hi @Kandr0s 

I was able to reproduce the behavior you reported. I've put together a fix that should address this, it is working locally for me. Would you mind pulling down the latest master from the test suite and give it a try on your API 19 emulator and/or device? We look forward to receiving your feedback. Thanks!

**Comment by Kandr0s** [comment]
Hi @developernotes 

The Error appears to be fixed. Haven't got any crashes on my Emulators/Devices.

**Comment by developernotes** [comment]
Hello @Kandr0s 

Excellent, and again thank you for the report. We will release a new build shortly. Thanks!
