### ISSUE TITLE
net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database

### ISSUE THREAD

**Issue by c765657797z** [sqlcipher/sqlcipher-android-tests#27]
Hi,
I'm facing the below issue:
net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
I used the combination of GreenDao and Sqlcipher,Occasional issue

**Comment by developernotes** [comment]
Hi @c765657797z 

Are you able to replicate this issue outside of GreenDao? If so, we would be happy to look into this further with some additional information.

- What Android OS version are you running with this error?
- Where does the database exist on device?
- Does your application attempt to open a database in read-only mode?
- Can you provide some additional context around what is occurring in the application/library when the error occurs?

**Comment by c765657797z** [comment]
@developernotes 
Thanks a lot for your reply.
GreenDao is the database of my project. I am recommended to encrypt database with sqlcipher on the official site of GreenDao. All configuration is followed by the official documents.

To respond your questions:
1. Error occurs on any version higher than Android 5.0
2. Database exists in Device RAM
3. It is in read&write mode while my application attempt to open a database.
4. more additional information: I can encrypt database with sqlcipher. It will cause crashes to operate database frequently, including query, write, read, delete and so on. I checked the crash log and it shows read-only mode crash. Our database is good before encrypting database with sqlcipher.

Any advice would be highly appreciated.

Thanks again.

**Comment by c765657797z** [comment]
@developernotes 
this is the error log

E/AndroidRuntime: FATAL EXCEPTION: pool-22-thread-1
                                                                        Process: com.sisisan.batmessage, PID: 23657
                                                                        net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database
                                                                            at net.sqlcipher.database.SQLiteStatement.native_execute(Native Method)
                                                                            at net.sqlcipher.database.SQLiteStatement.executeInsert(SQLiteStatement.java:83)
                                                                            at org.greenrobot.greendao.database.EncryptedDatabaseStatement.executeInsert(EncryptedDatabaseStatement.java:46)
                                                                            at org.greenrobot.greendao.AbstractDao.insertInsideTx(AbstractDao.java:371)
                                                                            at org.greenrobot.greendao.AbstractDao.executeInsert(AbstractDao.java:351)
                                                                            at org.greenrobot.greendao.AbstractDao.insertOrReplace(AbstractDao.java:340)
                                                                            at com.sisisan.data.sql.sqlhelper.UserGroupChatMessageHelper.InsertData(UserGroupChatMessageHelper.java:225)
                                                                            at com.sisisan.data.sql.sqlhelper.UserGroupChatMessageHelper$3.run(UserGroupChatMessageHelper.java:478)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)

**Comment by c765657797z** [comment]
@developernotes 
When using sqlcipher, the database seems to have been deleted due to unknown reasons

**Comment by developernotes** [comment]
Hi @c765657797z 

A few follow up questions:

1. Are you able to reproduce the behavior outside of greenDao? Possibly within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests)?
2. The deleting of the database could be due to the [`DefaultDatabaseErrorHandler`](https://github.com/sqlcipher/android-database-sqlcipher/blob/master/android-database-sqlcipher/src/main/java/net/sqlcipher/DefaultDatabaseErrorHandler.java) implementation, which can be overridden in your `SQLiteOpenHelper` derived class.
3. You mention the database exists in device RAM, are you using `:memory:` as the filename, or a specific path on the device/emulator.

**Comment by bvk070** [comment]
net.sqlcipher.database.SQLiteException: error code 8: attempt to write a readonly database

I am able to reproduce this crash. This crash occurs once migration is done and when we try to write/read from database. It gives above exception. But when i restart the application. it is working fine.

Can you help me to fix this above exception?

**Comment by developernotes** [comment]
Hi @bvk070 

>I am able to reproduce this crash. 

Please create a replication test case within the SQLCipher for Android [test suite](https://github.com/sqlcipher/sqlcipher-android-tests). We would be happy to review this further once a test case is available.
